//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokter
    {
        public string KodeDokter { get; set; }
        public string NamaDokter { get; set; }
        public string JKelamin { get; set; }
    }
}
