//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kela()
        {
            this.Ruangs = new HashSet<Ruang>();
        }
    
        public string KodeKelas { get; set; }
        public string NamaKelas { get; set; }
        public Nullable<decimal> Harga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruang> Ruangs { get; set; }
    }
}
