//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Pasien
    {
        public string KodePasien { get; set; }
        public string NamaPasien { get; set; }
        public string Foto { get; set; }
        public HttpPostedFileBase[] LokasiFoto { get; set; }
    }
}
