//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruang
    {
        public string KodeRuang { get; set; }
        public string NamaRuang { get; set; }
        public string KodeKelas { get; set; }
    
        public virtual Kela Kela { get; set; }
    }
}
